#Dockerfile
 
# Use this image as the platform to build the app
FROM node:lts-alpine
 
# A small line inside the image to show who made it
LABEL Developers="Alexandre & Germain"
 
# The WORKDIR instruction sets the working directory for everything that will happen next
WORKDIR /app
 
# Copy all local files into the image
COPY . .

RUN npm install 
# Build SvelteKit app
RUN npm run build
 
# The USER instruction sets the user name to use as the default user for the remainder of the current stage
USER node:node
 
CMD [ "node","build/index.js" ]