import type {Advertisements} from "$lib/models/advertisements";
import {ContractType} from "$lib/models/contractType";

export let mockAdverts: Advertisements[] = [
    {
        title: "Software Developer",
        smallDescription: "This is a small description",
        salary: 1000,
        localization: "London",
        contractType: ContractType.fixedTerm,
        company: "Company 1",

    },
    {
        title: "Software Developer",
        smallDescription: "This is a small description",
        salary: 1000,
        localization: "London",
        contractType: ContractType.permanent,
        company: "Company 2",
    },
    {
        title: "Software Developer",
        smallDescription: "This is a small description",
        salary: 1000,
        localization: "London",
        contractType: ContractType.internship,
        company: "Company 3",
    },
    {
        title: "Software Developer",
        smallDescription: "This is a small description",
        salary: 1000,
        localization: "London",
        contractType: ContractType.freelance,
        company: "Company 4",
    },
    {
        title: "Software Developer",
        smallDescription: "This is a small description",
        salary: 1000,
        localization: "London",
        contractType: ContractType.other,
        company: "Company 5",
    },
    {
        title: "Software Developer",
        smallDescription: "This is a small description",
        salary: 1000,
        localization: "London",
        contractType: ContractType.fixedTerm,
        company: "Company 6",
    },
    {
        title: "Software Developer",
        smallDescription: "This is a small description",
        salary: 1000,
        localization: "London",
        contractType: ContractType.permanent,
        company: "Company 7",
    },
    {
        title: "Software Developer",
        smallDescription: "This is a small description",
        salary: 1000,
        localization: "London",
        contractType: ContractType.internship,
        company: "Company 8",
    },
    {
        title: "Software Developer",
        smallDescription: "This is a small description",
        salary: 1000,
        localization: "London",
        contractType: ContractType.freelance,
        company: "Company 9",
    },
    {
        title: "Software Developer",
        smallDescription: "This is a small description",
        salary: 1000,
        localization: "London",
        contractType: ContractType.other,
        company: "Company 10",
    },
];